- id: git-status
  name: git-status
  description: "todo"
  entry: python ../django-translation-checker-pre-commit/main.py
  language: python
  types_or: [python]
  args: [--noodle, a.py, b.py]
  require_serial: true
  additional_dependencies: []
